# Install and configure Redis
---

- dynamic_defaults:
    hostvars: '{{ hostvars[inventory_hostname] }}'
    defaults: '{{ redis_dynamic_defaults }}'
    must_match: yes
  tags: [redis, always]

- block:
    - include_tasks: setup-repository-{{ ansible_pkg_mgr }}.yml

    - name: Install Redis packages
      package:
        name: '{{ redis_packages }}'
        state: present
  become: yes
  tags: [redis, packages]

- block:
    - name: Detect Redis version
      shell:
        redis-server -v | egrep -o 'Redis server v=[0-9](\.[0-9]+)+' | cut -d= -f 2
      changed_when: no
      check_mode: no
      register: _redis_version

    - set_fact:
        redis_version: '{{ _redis_version.stdout }}'

    - debug:
        msg: 'Redis version {{ redis_version }}'

    - name: Configure Redis
      template:
        src: '{{ item }}'
        dest: '{{ redis_config_path }}'
        mode: 0644
      become: yes
      notify: restart redis
      with_first_found:
        - redis.conf.{{ redis_version }}.j2
        - redis.conf.{{ redis_version.split('.')[:-1]|join('.') }}.j2
        - redis.conf.{{ redis_version.split('.')[:-2]|join('.') }}.j2
  tags: [redis, config]

- name: Start Redis service
  service:
    name: '{{ redis_service }}'
    enabled: yes
    state: started
  become: yes
  tags: [redis, services]

- block:
    - meta: flush_handlers

    - name: Benchmark Redis
      command:
        redis-benchmark -q -n 10000 -c 50 -P 12
      changed_when: no
      check_mode: no
  tags: [redis, config]
